-- Sign up

insert into USERINFO values ('100100110', 'Mahesh', 'Elireddy', 'M', 'mahesh@blah.com' ,'1987-04-12', 
'Chapin Apt 1170,Health Drive','Stony Brook', 'NY' ,'11790', '214-240-8599');

insert into USERPASSWD values
('100100110','mahesh','mahesh@blah.com');

insert into userPreference values ('100100110','car');

-- Create Circles
insert into circle values ('8003','cse532','100100110');

-- Searching for users
select fname,lname from USERINFO where fname='Alice' or lname = 'McKeeny';

-- sending friend request
insert into friendRequest values ('100100101','100100110');

-- Accepting friend request

select fromUsrid from friendRequest where toUsrId='100100110';

insert into friend values ('100100101','100100110');
insert into friend values ('100100110','100100101');



-- List of friends
select usrid1 from friend where usrid2='100100110' ;

-- Add friend to circle
insert into circleMember values ('8003','100100101');

-- Create new SIP
insert into sip values ('1002','TEST');
-- Moderating SIP
insert into sipMember values ('1002','100100110','t');
-- New SIP page
insert into cseteam51.page values ('2003');
insert into cseteam51.sippage values ('2003','1002');

-- New SIP page post
insert into cseteam51.post values ('20121','2012-10-10','17:00','EST','Its Snowing!:D','100100110','2003');
-- Comment on a post
insert into cseteam51.comment values ('900011','2012-10-10','17:01','EST','Its beautiful! :)','100100110','20121');
--delete the comment
delete from COMMENT where commentId='900011' and authorId='100100110';
--delete SIP page post
delete from post where postid='20121' and author='100100110';

-- send message
insert into cseteam51.message values ('3011','2012-10-10','CSE532','Do u have assignent 1 questions?','100100110');
insert into cseteam51.msgReciever values ('3011','100100102');
insert into cseteam51.msgReciever values ('3011','100100110');

-- Delete message
delete from CSETEAM51.MSGRECIEVER where mesgid='3011' and recvId='100100110';
delete from CSETEAM51.MSGRECIEVER where mesgid='3011' and recvId='100100102';

-- Purchase Item
insert into cseteam51.sale values ('200010003','2012-04-22','33331','1','100100110');

-- Create an advertisement
insert into cseteam51.advt values ('33341','car','2012-04-10','ford','2012-Mustang','22010','30');
-- Delete an advertisement
delete from cseteam51.advt where advtid ='33341';

-- Sales report for the month of Apr-2012
select * from sale where saleDate > '2012-03-31' and saleDate < '2012-05-01';

--Listing of all the items being advertised on site 
select itemname,company,unitprice from advt;

-- List of items by item name

select sale.transId,itemname,saledate,sale.noUnits,userinfo.Fname from ADVT,SALE,USERINFO 
where  sale.advtid = advt.advtid and sale.userid = userinfo.id and advt.itemname='Superman Shirt';

-- list of items by customer name
select sale.transId,itemname,saledate,sale.noUnits,userinfo.Fname from ADVT,SALE,USERINFO 
where  sale.advtid = advt.advtid and sale.userid = userinfo.id and userinfo.fname='Alice';

--Revenue Generated by item type
select sum(unitPrice * sale.nounits),type from advt,sale 
where advt.type = 'car' and advt.advtid = sale.advtid group by(type);
-- Revenue Generated by item id
select sum(unitPrice * sale.nounits),itemname from advt,sale 
where advt.itemname = 'Superman Shirt' and advt.advtid = sale.advtid group by(itemname);
-- Revenue generated by customer
select sum(unitPrice * sale.nounits),Fname from advt,sale,USERINFO 
where sale.userid = userinfo.id and sale.advtid = advt.advtid and fname='Alice' group by(fname);
-- customer generated most total revenue
with tlusrrevn  as 
(select sum(unitPrice * sale.nounits) as a1,Fname from advt,sale,USERINFO 
where sale.userid = userinfo.id and sale.advtid = advt.advtid group by(fname))
select fname,a1 from tlusrrevn where a1 in (select max(a1) from tlusrrevn);
--product (ad/item) generated most total revenue
with tlitemrevn  as 
(select sum(unitPrice * sale.nounits) as a1,itemname from advt,sale 
where sale.advtid = advt.advtid group by(itemname))
select itemname,a1 from tlitemrevn where a1 in (select max(a1) from tlitemrevn);

--sorted list of sold items by number of units sold
select sale.nounits,itemname from sale,advt  where advt.advtid = sale.advtid order by(sale.nounits) DESC

--list of all customers who have purchased a particular item
select Fname from userinfo,sale,advt where advt.itemname='Superman Shirt' and advt.advtid = sale.advtid
and sale.userid = userinfo.id

-- all items for a given company sorted by number of units sold
select company,sale.nounits,itemname from sale,advt where sale.advtid=advt.advtid and company='ford' order by(sale.nounits) desc
--customer mailing lists for a given product
select userinfo.emailId from USERINFO,sale,advt where advt.advtid = sale.advtid and sale.userid = id
and ADVT.itemname='Superman Shirt'


--item suggestions for a given customer
select advt.itemname,advt.type,advt.company,advt.unitprice from advt where type in 
(select advt.type from USERINFO,sale,advt where advt.advtid = sale.advtid 
and sale.userid = id and USERINFO.fname='Alice')

-- Remove friend from circle 
delete from circleMember where memberId='100100101';

--delete a friend
delete from friend where usrid1='100100100' and usrid2='100100110';
delete from friend where usrid1='100100110' and usrid2='100100100';
-- Delete circles
delete from circle where circleid = '8003';


-- Remove friend request 
delete from friendRequest where fromUsrId='100100101' and toUsrId='100100110';
-- Delete user
delete from USERPASSWD where userid='100100110';
delete from USERPREFERENCE where userid='100100110';
delete from userinfo where id='100100110';
